name: aipo
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - brotli-python=1.0.9
  - ca-certificates=2025.12.2
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - cuda-cccl=13.1.115
  - cuda-cccl_win-64=13.1.115
  - cuda-cudart=12.1.105
  - cuda-cudart-dev=12.1.105
  - cuda-cupti=12.1.105
  - cuda-libraries=12.1.0
  - cuda-libraries-dev=12.1.0
  - cuda-nvrtc=12.1.105
  - cuda-nvrtc-dev=12.1.105
  - cuda-nvtx=12.1.105
  - cuda-opencl=13.1.115
  - cuda-opencl-dev=13.1.115
  - cuda-profiler-api=13.1.115
  - cuda-runtime=12.1.0
  - cuda-version=13.1
  - idna=3.7
  - khronos-opencl-icd-loader=2025.07.22
  - libcublas=12.1.0.26
  - libcublas-dev=12.1.0.26
  - libcufft=11.0.2.4
  - libcufft-dev=11.0.2.4
  - libcurand=10.4.1.81
  - libcurand-dev=10.4.1.81
  - libcusolver=11.4.4.55
  - libcusolver-dev=11.4.4.55
  - libcusparse=12.0.2.55
  - libcusparse-dev=12.0.2.55
  - libffi=3.4.4
  - libnpp=12.0.2.50
  - libnpp-dev=12.0.2.50
  - libnvjitlink=12.1.105
  - libnvjitlink-dev=12.1.105
  - libnvjpeg=12.1.1.14
  - libnvjpeg-dev=12.1.1.14
  - opencl-headers=2025.07.22
  - openssl=3.0.18
  - pip=24.2
  - pysocks=1.7.1
  - python=3.8.20
  - pytorch-cuda=12.1
  - sqlite=3.51.1
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - attrs==25.3.0
      - cffi==1.17.1
      - chumpy==0.70
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.1.1
      - coverage==7.6.1
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - cython==3.2.4
      - exceptiongroup==1.3.1
      - filelock==3.14.0
      - flake8==7.1.2
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - interrogate==1.7.0
      - isort==4.3.21
      - jinja2==3.1.6
      - jmespath==0.10.0
      - json-tricks==3.17.3
      - kiwisolver==1.4.7
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mmcv==2.1.0
      - mmdet==3.2.0
      - mmengine==0.10.7
      - model-index==0.1.11
      - mpmath==1.3.0
      - munkres==1.1.4
      - networkx==3.1
      - numpy==1.24.4
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.0.3
      - parameterized==0.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - py==1.11.0
      - pycocotools==2.0.7
      - pycodestyle==2.12.1
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pyflakes==3.2.0
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pytest==8.3.5
      - pytest-runner==6.0.1
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pywin32==311
      - pyyaml==6.0.3
      - regex==2024.11.6
      - requests==2.28.2
      - rich==13.4.2
      - scipy==1.10.1
      - setuptools==60.2.0
      - shapely==2.0.7
      - six==1.17.0
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - terminaltables==3.1.10
      - tomli==2.4.0
      - torch==2.4.1+cu121
      - torchvision==0.19.1+cu121
      - tqdm==4.65.2
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - urllib3==1.26.20
      - xdoctest==1.3.0
      - xtcocotools==1.14.3
      - yapf==0.43.0
      - zipp==3.20.2
